### ISSUE TITLE
"Goal should not be automatically accomplished" policy when creating a Goal

### ISSUE THREAD

**Issue by bgord** [bgord/trackers#1]
User story:

As a User, I want to create a Goal for a Tracker that is not accomplished yet basing on the current Tracker Value, so that I can have a clear vision of the path to accomplish the Goal.

INFO:
- One Tracker can have only one Goal
- Goal can be created only for an *active* Tracker
- Goal can be displayed both for *active* and *archived* Trackers
- Goal can be added for all kinds of Trackers (*counter* and *one value* now)

Scenario 1

The User wants to create a Goal for an *archived* Tracker

Given the User has an *archived* Tracker
When given Tracker doesn't have a Goal
Then no Create Goal UI is displayed

Scenario 2

The User wants to create a Goal for an *active* Tracker without a goal

Given the User has an *active* Tracker
When the Tracker has no Goal
Then the Create Goal UI is displayed

Scenario 3

The User wants to create a *minimum* Goal for an *active* Tracker

Given the User has an *active* Tracker
Given the user wants to create a *minimum* Goal
When the current Tracker Value is greater than the *minimum* Goal Target
Then the error toast is displayed with the "Goal would be automatically accomplished" text

E.g the "Books read" Tracker has a current Tracker Value of 10, and the User tries to create a *minimum* Goal with Goal Target of 5.

Scenario 4

The User wants to create a *maximum* Goal for an *active* Tracker

Given the User has an *active* Tracker
Given the user wants to create a *maximum* Goal
When the current Tracker Value is already smaller than the *maximum* Goal Target
Then the error toast is displayed with the "Goal would be automatically accomplished" text

E.g the "Weight" Tracker has a current Tracker Value of 75, and the User tries to create a *maximum* Goal with Goal Target of 80.

<img width="487" alt="Screenshot 2023-06-25 at 11 07 58" src="https://github.com/bgord/trackers/assets/23278550/b43c030b-a7f9-45d7-9c34-ccdc4e9485eb">

**Comment by Gajosen** [comment]
Test case 3

Preconditions:

The user is logged in.
The user is on the main page.
The user has an available active tracker with no goal.

Test case 1: Checking if there is no opportunity to create a goal for active tracker with no goal.

Find an active tracker with no goal on the main page.
Click on the expander on the left side of the tracker.
Expected result: The Create Goal UI shoul be displayed

Actual result: [passed] The Create Goal UI is displayed.

Browsers:

Chrome 114.0.5735.134
desktop [passed]
mobile (min width: 320px) [passed]
Firefox 113.0.1
desktop [passed]
mobile (min width: 320px) [passed]

**Comment by Gajosen** [comment]
Preconditions:

The user is logged in.
The user is on the main page.
The user has an available active tracker with the goal.

Test case 1: Checking if  the error toast is displayed with the "Goal would be automatically accomplished" text when the current Tracker Value is greater than the minimum Goal Target

1. Find an active tracker with the goal on the main page.
2. Click on the expander on the left side of the tracker.
3. Complete Tracker Value with the bigger value than the goal, e.g. when the goal is "10", write "11" value.
4. Click "Sync"

Expected result: The error toast should be displayed with the "Goal would be automatically accomplished" text when the current Tracker Value is greater than the minimum Goal Target

Actual result: [failed] The text of the error is different: Tracker datapoint synced

Browsers:

Chrome 114.0.5735.134
desktop [failed]
mobile (min width: 320px) [failed]
Firefox 113.0.1
desktop [failed]
mobile (min width: 320px) [failed]

![image](https://github.com/bgord/trackers/assets/80550549/f94a3f99-f4a9-4baf-bcab-cba4b7f08a4e)

**Comment by Gajosen** [comment]
Preconditions:

The user is logged in.
The user is on the main page.
The user has an available active tracker

Test case 4: Checking if the error toast is displayed with the "Goal already accomplished" text when the current Tracker Value is already smaller than the maximum Goal Target

1. Click the expander of the chosen tracker.
2. Complete the tracker value without clicking SYNC
3. Complete the maximum goal with the greater number than tracker value

Expected result: The error toast is displayed with the "Goal already accomplished" text

Actual result: [passed] 

Browsers:

Chrome 114.0.5735.134
desktop [passed]
mobile (min width: 320px) [passed]
Firefox 113.0.1
desktop [passed]
mobile (min width: 320px) [passed]
